version: "3.9"

services:
  frontend:
    image: alto64/svelte-linksharingapp:latest
    container_name: svelte-linksharingapp_frontend
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - app_network

  backend:
    image: alto64/flask-linksharingapp:latest
    container_name: flask-linksharingapp
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app_network

  caddy:
    image: caddy:alpine
    container_name: caddy-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network: {}
