name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy IaC
    runs-on: ubuntu-latest

    steps:
      - name: Check out IaC repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy Infrastructure via SSH
        uses: appleboy/ssh-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
          script: |
            cd /srv/link-sharing-app
            echo "DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME"
            echo "DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN"
            if [ ! -d .git ]; then
              git clone https://github.com/MateuszSzczukiewicz/link-sharing-app-iac.git .
            else
              git config pull.rebase false
              git pull origin main
            fi

            cd docker-compose
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose pull
            docker-compose up -d
