name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy IaC to Server
    runs-on: ubuntu-latest

    steps:
      - name: Check out IaC repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy Infrastructure via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/link-sharing-app
            if [ ! -d .git ]; then
              git clone https://github.com/MateuszSzczukiewicz/link-sharing-app-iac.git .
            else
              git pull origin main
            fi

            cd docker-compose
            docker-compose pull
            docker-compose up -d
